name: Build binary

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
        with:
          path: storage

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Checkout cpu_features.NET
        uses: actions/checkout@v3
        with:
          repository: toor1245/cpu_features.NET
          path: cpu_features.NET
      
      - name: Cache CMake project
        id: project
        uses: actions/cache@v3
        with:
          path: cpu_features.NET
          key: project-${{ hashFiles('./cpu_features.NET/*') }}

      - name: Configure CMake project
        if: steps.project.outputs.cache-hit != 'true'
        run: |
          cd cpu_features.NET
          cmake . -Bcmake-build-release -DCMAKE_BUILD_TYPE=Release -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

      - name: Build CMake project
        run: |
          cd cpu_features.NET
          cmake --build cmake-build-release --config=Release

      # TODO: make it depend on version?
      - name: Copy dll
        run: |
          mkdir -p ./storage/runtimes/win-x64/native/
          cp ./cpu_features.NET/cmake-build-release/lib/cpu_features_dotnet.x64.dll ./storage/runtimes/win-x64/native/

      - name: Deploy
        uses: moodiest/push-to-branch-action@develop
        env:
          REPO: self
          BRANCH: "create-pull-request/patch"
          FOLDER: storage
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
