name: Build binary

on:
  pull_request:
    branches: 
      - main
  #workflow_dispatch: # TODO: replace ${{github.head_ref}} for workflow_dispatch...

jobs:
  build:
    name: Test build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - { os: windows-latest, rid: win-x64 }
        - { os: ubuntu-22.04, rid: linux-x64 }
        - { os: macos-latest, rid: mac-x64 }
    steps:
      - name: Echo branch name
        run: echo ${{github.head_ref}} 

      - name: Checkout current repo
        uses: actions/checkout@v3
        with:
          ref: ${{github.head_ref}}
          path: storage

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Test Ninja
        run: ninja --version && ls ninja-build

      - name: Checkout cpu_features.NET
        uses: actions/checkout@v3
        with:
          repository: toor1245/cpu_features.NET
          path: cpu_features.NET

      - name: Cache CMake project
        id: project
        uses: actions/cache@v3
        with:
          path: cpu_features.NET/cmake-build-release
          key: project-${{ hashFiles('./cpu_features.NET/src/*') }}

      - name: Configure CMake project
        if: steps.project.outputs.cache-hit != 'true'
        run: |
          cd cpu_features.NET
          ${{ runner.os!='Windows'&&'sudo '||''}}cmake . -Bcmake-build-release -DCMAKE_BUILD_TYPE=Release ${{ runner.os=='Windows'&&'-GNinja'||''}} -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

      - name: Build CMake project
        run: ${{ runner.os!='Windows'&&'sudo '||''}}cmake --build "cpu_features.NET/cmake-build-release" --config=Release

      # TODO: make it depend on version?
      - name: Copy Binary
        shell: bash
        run: |
          ls ./cpu_features.NET/cmake-build-release/lib/
          mkdir -p ./storage/runtimes/${{ matrix.rid }}/native/
          cp ./cpu_features.NET/cmake-build-release/lib/cpu_features_dotnet.x64.* ./storage/runtimes/${{ matrix.rid }}/native/

      - name: Git Push
        run: |
          cd storage
          git status
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -m "Add ${{ matrix.rid }} binary"
          git push origin ${{github.head_ref}}
