name: Build binary

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: toor1245/cpu_features.NET
          path: cpu_features.NET

      - name: Configure CMake project
        run: |
          cd cpu_features.NET
          cmake . -Bcmake-build-release -DCMAKE_BUILD_TYPE=Release -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

      - name: Configure CMake project
        run: |
          cd cpu_features.NET
          cmake --build cmake-build-release --config=Release

      # TODO: make it depend on version?
      - name: Copy dll
        run: |
          mkdir -p ./runtimes/win-x64/native/
          cp ./cpu_features.NET/cmake-build-release/lib/cpu_features_dotnet.x64.dll ./runtimes/win-x64/native/
          ls ./runtimes/win-x64/native/
      - uses: nelonoel/branch-name@v1.0.1
      - name: Deploy
        uses: moodiest/push-to-branch-action@develop
        env:
          REPO: self
          BRANCH: ${BRANCH_NAME}
          FOLDER: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
