name: Create Nuget package

on:
  pull_request: #TODO: add pattern
    branches: 
      - main
  #workflow_dispatch: # TODO: replace ${{github.head_ref}} with github.ref parsing for workflow_dispatch...

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include: 
        - { os: windows-latest }
        - { os: ubuntu-22.04 }
        - { os: macos-latest }
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
        with:
          ref: ${{github.head_ref}}
          path: storage

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Checkout cpu_features.NET
        uses: actions/checkout@v3
        with:
          repository: toor1245/cpu_features.NET
          path: cpu_features.NET

      - name: Configure CMake project
        run: ${{ runner.os!='Windows'&&'sudo '||''}}cmake "cpu_features.NET" -Bcmake-build-release -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DCPU_FEATURES_DOTNET_PACKAGE_OUTPUT_PATH="${{github.workspace}}/storage"

      - name: Build CMake project
        run: ${{ runner.os!='Windows'&&'sudo '||''}}cmake --build "cmake-build-release" --config=Release

      - name: cpu_features_dotnet_runtime_package
        run: ${{ runner.os!='Windows'&&'sudo '||''}}cmake --build "cmake-build-release" --config=Release --target=cpu_features_dotnet_runtime_package

      - name: Git Push
        run: |
          cd storage
          git pull
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -m "Add ${{ matrix.os }} Nuget package"
          git push origin ${{github.head_ref}}

  nuget:
    name: Create Nuget package
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout cpu_features.NET
        uses: actions/checkout@v3
        with:
          repository: toor1245/cpu_features.NET
          path: cpu_features.NET

      - name: Checkout current repo
        uses: actions/checkout@v3
        with:
          ref: ${{github.head_ref}}
          path: storage

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3

      - name: Configure CMake project
        run: ${{ runner.os!='Windows'&&'sudo '||''}}cmake "cpu_features.NET" -Bcmake-build-release -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DCPU_FEATURES_DOTNET_PACKAGE_OUTPUT_PATH="${{github.workspace}}/storage"

      - name: cpu_features_dotnet_runtime_package
        run: ${{ runner.os!='Windows'&&'sudo '||''}}cmake --build "cmake-build-release" --config=Release --target=cpu_features_dotnet_package
       
      - name: Upload Nuget to artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          path: storage/*.nupkg

      - name: Git Push
        run: |
          cd storage
          git pull
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -m "Add general Nuget package"
          git push origin ${{github.head_ref}}

  test-nuget:
    name: Test Nuget
    needs: nuget
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include: 
        - { os: windows-latest }
        - { os: ubuntu-22.04 }
        - { os: macos-latest }
    steps:
      - name: Checkout cpu_features.NET
        uses: actions/checkout@v3
        with:
          repository: toor1245/cpu_features.NET
          path: cpu_features.NET

      - name: Checkout current repo
        uses: actions/checkout@v3
        with:
          ref: ${{github.head_ref}}
          path: storage

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x

      - name: Configure CMake project
        run: ${{ runner.os!='Windows'&&'sudo '||''}}cmake "cpu_features.NET" -Bcmake-build-release -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DCPU_FEATURES_DOTNET_PACKAGE_OUTPUT_PATH="${{github.workspace}}/storage"

      - name: Add NuGet package to tests
        run: ${{ runner.os!='Windows'&&'sudo '||''}}cmake --build cmake-build-release --config=Release --target add_nuget_package_to_tests

      - name: Create build
        run: ${{ runner.os!='Windows'&&'sudo '||''}}dotnet build "src/CpuFeaturesDotNet" -c Release --force

      - name: Run Unit Tests for .Net Core 3.1
        run: ${{ runner.os!='Windows'&&'sudo '||''}}dotnet test "tests" -c Release -f netcoreapp3.1

      - name: Run Unit Tests for .Net 5.0
        run: ${{ runner.os!='Windows'&&'sudo '||''}}dotnet test "tests" -c Release -f net5.0
